name: Publish Package

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bun
        uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build

      - name: Publish package
        uses: oven-sh/setup-bun@v1
        with:
          command: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
