name: Publish Package

on:
  pull_request:
    types:
      - closed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bun
        uses: oven-sh/setup-bun@v1
        with:
          # run any `bun` or `bunx` command
          - run: bun install
          - run: bun run build

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
